# Basic
name:               "Intelligent Systems Phystech"
# title:              "Intelligent Systems at Moscow Institute of Physics and Technology"
# description:        "this is a page for Intelligent Systems at the Moscow Institute of Physics and Technology, Moscow"


# URL
url:                https://intelligent-systems-phystech.github.io
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin

languages: ["en"]

exclude_from_localizations: ["images"]


# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "lecturers"
    href:           "/people"
  - name:           "courses"
    href:           "/course"
  - name:           "materials"
    href:           "/materials"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  - scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  - scope:
      path:         ""
      type:         "materials"
    values:
      layout:       "page"
  - scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  - scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"
  - scope:
      path:         ""
      type:         "course"
    values:
      layout:       "course"

collections:
  people:
    output: true
    permalink: /people/:title/index.html
  course:
    output: true
    permalink: /course/:title/index.html


global:
  course:
    types:
      - id: bachelor
        name: Bachelor
      - id: master
        name: Master
  people:
    roles:
      - id: hotd
        name: Head of the Department
      - id: dos
        name: Doctor of Science
      - id: phd
        name: Ph.D
      - id: gs
        name: Graduate Student
      - id: student
        name: Student
      - id: template
        name: TEMPLATE