# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Machine Learning Phystech"
title:              "Intelligent Systems at Moscow Institute of Physics and Technology"
description:        "this is a page for Intelligent Systems at the Moscow Institute of Physics and Technology, Moscow"


# URL
url:                https://intelligent-systems-phystech.github.io
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "people"
    href:           "/people"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
